apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-tech-deployment
  labels:
    app: ab-tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ab-tech
  template:
    metadata:
      labels:
        app: ab-tech
    spec:
      containers:
        - name: ab-tech
          image: jsachdev07/ab_tech:3   # placeholder for Jenkins build number
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
